### ISSUE TITLE
[web] Store databases in database

### ISSUE THREAD

**Issue by at15** [xephonhq/awesome-time-series-database#38]
There has been projects putting information of database into database, i.e. https://github.com/cmu-db/dbdb.io which requires a python server and SQL database (and auth for public access). 

We serve the static website using gh-pages, so we can't use MySQL etc. However, there are many  database (even SQLish) using javascript and run in browser (w/o using WebSQL which is deprecated), we just need to figure out the schema, and turn our existing YAML files into other format. We want features like join so user can run query (and passing the query in the url should show the filtered result, which is [already supported ](https://xephonhq.github.io/awesome-time-series-database/?language=All&backend=Ceph))

## Databases that can run in browsers

- https://github.com/kripken/sql.js/ 3.9k star SQLite compiled to javascript using [emscripten](https://github.com/kripken/emscripten)
  - http://kripken.github.io/sql.js/GUI/ 
  - [Execute millions of sql statements in milliseconds](https://hackernoon.com/execute-millions-of-sql-statements-in-milliseconds-in-the-browser-with-webassembly-and-web-workers-3e0b25c3f1a6)
- https://github.com/agershun/alasql 2.9 k star 'JavaScript SQL database for browser and Node.js. Handles both traditional relational tables and nested JSON data (NoSQL). Export, store, and import data from localStorage, IndexedDB, or Excel'
- https://github.com/pouchdb/pouchdb 9.8k star 'store data locally while offline, then synchronize it with CouchDB and compatible servers when the application is back online'
- https://github.com/typicaljoe/taffydb 1.7k star , no SQL support, js
- https://github.com/louischatriot/nedb 7.5k star, 'Embedded persistent or in memory database for Node.js, nw.js, Electron and browsers, 100% JavaScript, no binary dependency. API is a subset of MongoDB's and it's plenty fast' 
- https://github.com/techfort/LokiJS/ 3.8 k in memory document

## TODO

-  [ ] pick one that can be integrated w/ nuxt.js (vue) (l think there might be some react binding, but no for vue ...)
- [ ] update the script, and extend YAML format to address problems like license #34 
- [ ] db specific detail, might include content from previous survey and blogs (also other people's blog)
- [ ] close tons of issues .... wow, so many time series, such database
- [ ] use nelify for PR so we can have preview before merge
- [ ] update .github for issue template, we now have benchmark, blog etc. instead of just database
- [ ] make use of new dropdown feature github markdown (actually it's HTML `<details>` and `<summary>`... not gfm ...)

**Comment by at15** [comment]
fork the official performance test, alasql seems to be faster (but it can't read sqlite file unless sql.js is used), it can export to csv, xlsx though .... https://jsperf.com/sql-js-vs-alasql-js-fork (the original one is broken due to https https://jsperf.com/sql-js-vs-alasql-js)
